name: parul_seminar
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Animation :
  loading_animation_widget: 1.2.1

  # Ui utills :
  intl: ^0.19.0
  flutter_svg: 2.0.10+1

  # Firebase:
  firebase_core: 3.3.0
  firebase_auth: 5.1.4
  cloud_firestore: 5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/icons/

  fonts:
    - family: public_sans
      fonts:
        - asset: assets/fonts/public_sans/PublicSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/public_sans/PublicSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/public_sans/PublicSans-Light.ttf
          weight: 300
        - asset: assets/fonts/public_sans/PublicSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/public_sans/PublicSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/public_sans/PublicSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/public_sans/PublicSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/public_sans/PublicSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/public_sans/PublicSans-Black.ttf
          weight: 900
