// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2drsE4j3twlm0G6Aln2DR5rNgEaadBnc',
    appId: '1:93195601163:web:bddac04e3b8c72776e0e0e',
    messagingSenderId: '93195601163',
    projectId: 'parul-auth',
    authDomain: 'parul-auth.firebaseapp.com',
    storageBucket: 'parul-auth.appspot.com',
    measurementId: 'G-MPZ1GMRRQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvYl1VuE4KW0Wur-NwNUy5eil7cbhGfOY',
    appId: '1:93195601163:android:88517260b7b01a276e0e0e',
    messagingSenderId: '93195601163',
    projectId: 'parul-auth',
    storageBucket: 'parul-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNbfz_RnXUQXHXdlfJ65O_XxSIB2YrHDQ',
    appId: '1:93195601163:ios:a5c673443dddaaf96e0e0e',
    messagingSenderId: '93195601163',
    projectId: 'parul-auth',
    storageBucket: 'parul-auth.appspot.com',
    iosBundleId: 'com.parul.auth',
  );
}
